### ISSUE TITLE
Don't store interpolators in model classes

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/bmlab#7]
@raimund-schluessler:
Currently we are storing interpolators as instance variables of model classes, for example:

```python
        # If we only have one entry we always return the same value
        if len(sorted_keys) < 2:
            self.extraction_angles_interpolation =\
                lambda idx, time: extraction_angles_array[0]
        # Otherwise we can interpolate
        else:
            self.extraction_angles_interpolation = interpolate.interp2d(
                self.extraction_angles_index,
                calib_times_array,
                extraction_angles_array)
```

in `bmlab.models.extraction_model`. This is a problem for serializing the model to HDF. It would be better if instance variables of model classes could only point to data, not to callables.

**Comment by raimund-schluessler** [comment]
Ok, fine with me.
What would you propose where to store them? They only need to be recreated/updated when the underlying data changes, so we could create them from the data again once a file was loaded.

**Comment by matthias-baer** [comment]
How about having a class `bmlab.fits.CircleFitInterpolation` that holds a reference to the `ExtractionModel` instance. Whenever the data in the model changes, the interpolator in `CircleFitInterpolation` refreshes. This could be  triggered using the observer pattern or alternatively manually by whoever uses an CircleFitInterpolation instance. What do you think?

**Comment by matthias-baer** [comment]
Forget about the observer pattern. I guess that would cause more problems for serialization. :-)

**Comment by raimund-schluessler** [comment]
Then let's move it to a separate class and refresh it manually. And we will need something similar for the `CalibrationModel` to interpolate the frequencies between calibrations.

**Comment by matthias-baer** [comment]
Ok, but before doing that let me restructure a little bit the extraction model as an example how I think we should restructure the design. Basically we need a service layer between model classes and users of the model classes.

**Comment by matthias-baer** [comment]
While implementing, I changed my mind. I will modify the serializer instead and leave the model classes as they are.
